import { Job, UserProfile, Application } from "@/types";

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const jobs: Job[] = [
  {
    id: "job-1",
    title: "Frontend Developer Intern",
    company: "PixelForge Labs",
    companyLogo: "https://logo.clearbit.com/vercel.com",
    location: "Hyderabad, Telangana",
    latitude: 17.385,
    longitude: 78.4867,
    salaryMin: 15000,
    salaryMax: 25000,
    salaryPeriod: "month",
    experience: "undergraduate",
    education: "B.Tech / BCA (pursuing or completed)",
    jobType: "internship",
    workMode: "hybrid",
    categories: ["internships", "undergraduate", "it-software"],
    postedDate: daysAgo(2),
    deadline: daysFromNow(18),
    description:
      "Work alongside senior engineers building customer-facing dashboards in React and TypeScript. Great for students who want production experience before graduating.",
    responsibilities: [
      "Build and style UI components with React and Tailwind CSS",
      "Fix bugs reported by QA and collaborate in daily standups",
      "Write basic unit tests for new components",
    ],
    requirements: [
      "Currently pursuing or recently completed a Bachelor's in CS/IT",
      "Basic knowledge of JavaScript, HTML, CSS",
      "Familiarity with Git",
    ],
    skills: ["React", "JavaScript", "HTML", "CSS", "Git"],
    applyMethod: "one-click",
  },
  {
    id: "job-2",
    title: "Data Analyst - Fresher",
    company: "Northwind Analytics",
    companyLogo: "https://logo.clearbit.com/tableau.com",
    location: "Hyderabad, Telangana",
    latitude: 17.4239,
    longitude: 78.4738,
    salaryMin: 400000,
    salaryMax: 550000,
    salaryPeriod: "year",
    experience: "fresher",
    education: "B.Sc/B.Tech in Statistics, CS, or related field",
    jobType: "full-time",
    workMode: "on-site",
    categories: ["fresher", "data-science", "analytics"],
    postedDate: daysAgo(1),
    deadline: daysFromNow(25),
    description:
      "Join our analytics team to turn raw data into actionable insights for retail clients. Training provided on internal tooling.",
    responsibilities: [
      "Clean and analyze datasets using SQL and Python",
      "Build dashboards in Power BI for client reporting",
      "Present findings to cross-functional teams",
    ],
    requirements: [
      "Bachelor's degree in a quantitative field",
      "Working knowledge of SQL and Excel",
      "Exposure to Python or R is a plus",
    ],
    skills: ["SQL", "Python", "Power BI", "Excel"],
    applyMethod: "one-click",
  },
  {
    id: "job-3",
    title: "Software Engineer II",
    company: "Vertex Cloud Systems",
    companyLogo: "https://logo.clearbit.com/atlassian.com",
    location: "Bengaluru, Karnataka",
    latitude: 12.9716,
    longitude: 77.5946,
    salaryMin: 1200000,
    salaryMax: 1800000,
    salaryPeriod: "year",
    experience: "1-3 years",
    education: "B.Tech/B.E in Computer Science or equivalent",
    jobType: "full-time",
    workMode: "hybrid",
    categories: ["it-software", "full-time", "graduate"],
    postedDate: daysAgo(4),
    deadline: daysFromNow(20),
    description:
      "Design and ship backend services powering our multi-tenant SaaS platform. Own features end to end alongside a small, senior team.",
    responsibilities: [
      "Develop and maintain microservices in Node.js and Go",
      "Participate in code reviews and system design discussions",
      "Improve CI/CD pipelines and observability",
    ],
    requirements: [
      "1-3 years of professional backend development experience",
      "Strong understanding of REST APIs and databases",
      "Experience with cloud platforms (AWS/GCP)",
    ],
    skills: ["Node.js", "Go", "AWS", "PostgreSQL", "Docker"],
    applyMethod: "external",
    externalApplyUrl: "https://example.com/careers/vertex-cloud/swe-ii",
  },
  {
    id: "job-4",
    title: "Government Junior Assistant",
    company: "Telangana State Public Services",
    location: "Hyderabad, Telangana",
    latitude: 17.3616,
    longitude: 78.4747,
    salaryMin: 25000,
    salaryMax: 35000,
    salaryPeriod: "month",
    experience: "fresher",
    education: "Any Bachelor's Degree",
    jobType: "full-time",
    workMode: "on-site",
    categories: ["government", "fresher", "graduate"],
    postedDate: daysAgo(6),
    deadline: daysFromNow(40),
    description:
      "Administrative role handling public records and citizen service requests at a district office. Recruitment via official state notification.",
    responsibilities: [
      "Process citizen applications and maintain records",
      "Assist senior officers with correspondence",
      "Ensure compliance with departmental procedures",
    ],
    requirements: [
      "Bachelor's degree from a recognized university",
      "Must clear the state public service exam",
      "Basic computer literacy",
    ],
    skills: ["MS Office", "Record Keeping", "Communication"],
    applyMethod: "external",
    externalApplyUrl: "https://example.gov.in/tspsc/notifications/junior-assistant",
  },
  {
    id: "job-5",
    title: "Digital Marketing Executive",
    company: "Brightwave Media",
    companyLogo: "https://logo.clearbit.com/hubspot.com",
    location: "Hyderabad, Telangana",
    latitude: 17.4483,
    longitude: 78.3915,
    salaryMin: 300000,
    salaryMax: 450000,
    salaryPeriod: "year",
    experience: "0-1 years",
    education: "Bachelor's in Marketing, Mass Comm, or related",
    jobType: "full-time",
    workMode: "on-site",
    categories: ["marketing", "fresher", "graduate"],
    postedDate: daysAgo(3),
    deadline: daysFromNow(15),
    description:
      "Plan and run paid social campaigns for D2C client brands, and report on performance weekly.",
    responsibilities: [
      "Manage Meta and Google Ads campaigns",
      "Create content calendars with the design team",
      "Track KPIs and prepare weekly performance reports",
    ],
    requirements: [
      "0-1 years experience in digital marketing (internships count)",
      "Familiarity with Meta Ads Manager or Google Ads",
      "Strong written communication",
    ],
    skills: ["SEO", "Google Ads", "Meta Ads", "Content Strategy"],
    applyMethod: "one-click",
  },
  {
    id: "job-6",
    title: "UI/UX Design Intern",
    company: "Studio Aperture",
    companyLogo: "https://logo.clearbit.com/figma.com",
    location: "Remote",
    latitude: 17.385,
    longitude: 78.4867,
    salaryMin: 10000,
    salaryMax: 18000,
    salaryPeriod: "month",
    experience: "undergraduate",
    education: "Design, HCI, or any Bachelor's degree",
    jobType: "internship",
    workMode: "remote",
    categories: ["internships", "design", "remote", "undergraduate"],
    postedDate: daysAgo(1),
    deadline: daysFromNow(22),
    description:
      "Support the design team in wireframing and prototyping features for a productivity app used by 200k+ users.",
    responsibilities: [
      "Create wireframes and interactive prototypes in Figma",
      "Participate in user research sessions",
      "Maintain and extend our design system",
    ],
    requirements: [
      "Portfolio demonstrating UI/UX fundamentals",
      "Proficiency with Figma",
      "Currently enrolled in a Bachelor's program",
    ],
    skills: ["Figma", "Wireframing", "Prototyping", "Design Systems"],
    applyMethod: "one-click",
  },
  {
    id: "job-7",
    title: "Customer Support Associate",
    company: "HelpDesk Nexus",
    location: "Hyderabad, Telangana",
    latitude: 17.4126,
    longitude: 78.4482,
    salaryMin: 18000,
    salaryMax: 26000,
    salaryPeriod: "month",
    experience: "fresher",
    education: "Any Bachelor's Degree / Intermediate",
    jobType: "full-time",
    workMode: "on-site",
    categories: ["customer-support", "fresher", "part-time"],
    postedDate: daysAgo(5),
    deadline: daysFromNow(12),
    description:
      "Handle inbound customer queries via chat and phone for a fintech app, with rotational shifts.",
    responsibilities: [
      "Resolve customer queries within SLA",
      "Log tickets accurately in the CRM",
      "Escalate complex issues to the right team",
    ],
    requirements: [
      "Good spoken and written English/Hindi",
      "Comfortable with rotational shifts",
      "Basic computer skills",
    ],
    skills: ["Communication", "CRM", "Problem Solving"],
    applyMethod: "one-click",
  },
  {
    id: "job-8",
    title: "Part-Time Content Writer",
    company: "WordCraft Studio",
    location: "Remote",
    latitude: 17.385,
    longitude: 78.4867,
    salaryMin: 8000,
    salaryMax: 15000,
    salaryPeriod: "month",
    experience: "undergraduate",
    education: "Any Bachelor's (pursuing or completed)",
    jobType: "part-time",
    workMode: "remote",
    categories: ["part-time", "remote", "undergraduate", "marketing"],
    postedDate: daysAgo(2),
    deadline: daysFromNow(30),
    description:
      "Write blog posts and product copy for SaaS clients, roughly 15-20 hours a week, fully flexible schedule.",
    responsibilities: [
      "Research and write 4-6 articles per month",
      "Collaborate with editors on tone and structure",
      "Optimize content for SEO",
    ],
    requirements: [
      "Strong written English",
      "Basic understanding of SEO",
      "Ability to meet deadlines independently",
    ],
    skills: ["Writing", "SEO", "Research"],
    applyMethod: "one-click",
  },
  {
    id: "job-9",
    title: "Machine Learning Engineer",
    company: "Nimbus AI",
    companyLogo: "https://logo.clearbit.com/openai.com",
    location: "Hyderabad, Telangana",
    latitude: 17.4399,
    longitude: 78.3489,
    salaryMin: 1500000,
    salaryMax: 2400000,
    salaryPeriod: "year",
    experience: "3-5 years",
    education: "B.Tech/M.Tech in CS or related, MS preferred",
    jobType: "full-time",
    workMode: "hybrid",
    categories: ["data-science", "it-software", "full-time"],
    postedDate: daysAgo(7),
    deadline: daysFromNow(21),
    description:
      "Build and deploy ML models for demand forecasting used across our logistics network.",
    responsibilities: [
      "Design and train forecasting models",
      "Deploy models to production with monitoring",
      "Collaborate with data engineers on pipelines",
    ],
    requirements: [
      "3-5 years experience in ML engineering",
      "Strong Python and PyTorch/TensorFlow skills",
      "Experience with MLOps tooling",
    ],
    skills: ["Python", "PyTorch", "MLOps", "SQL", "Docker"],
    applyMethod: "external",
    externalApplyUrl: "https://example.com/careers/nimbus-ai/ml-engineer",
  },
  {
    id: "job-10",
    title: "Financial Analyst - Graduate Program",
    company: "Meridian Capital Advisors",
    companyLogo: "https://logo.clearbit.com/jpmorgan.com",
    location: "Hyderabad, Telangana",
    latitude: 17.4065,
    longitude: 78.4772,
    salaryMin: 600000,
    salaryMax: 800000,
    salaryPeriod: "year",
    experience: "fresher",
    education: "B.Com/BBA/B.Tech with strong quantitative skills",
    jobType: "full-time",
    workMode: "on-site",
    categories: ["finance", "graduate", "fresher"],
    postedDate: daysAgo(3),
    deadline: daysFromNow(28),
    description:
      "Two-year rotational graduate program covering equity research, risk, and portfolio analytics.",
    responsibilities: [
      "Support senior analysts with financial modeling",
      "Prepare client-facing research summaries",
      "Rotate across three business units over two years",
    ],
    requirements: [
      "Bachelor's degree with strong academic record",
      "Comfortable with Excel-based financial modeling",
      "CFA Level 1 (in progress) is a plus",
    ],
    skills: ["Excel", "Financial Modeling", "Valuation"],
    applyMethod: "one-click",
  },
  {
    id: "job-11",
    title: "Business Analytics Intern",
    company: "Northwind Analytics",
    companyLogo: "https://logo.clearbit.com/tableau.com",
    location: "Hyderabad, Telangana",
    latitude: 17.4239,
    longitude: 78.4738,
    salaryMin: 12000,
    salaryMax: 20000,
    salaryPeriod: "month",
    experience: "undergraduate",
    education: "Pursuing Bachelor's in any quantitative discipline",
    jobType: "internship",
    workMode: "hybrid",
    categories: ["internships", "analytics", "undergraduate", "data-science"],
    postedDate: daysAgo(0),
    deadline: daysFromNow(20),
    description:
      "Shadow the analytics team on live client projects, with a strong chance of pre-placement offer.",
    responsibilities: [
      "Assist in building SQL queries and reports",
      "Support dashboard design in Power BI",
      "Document analysis methodology",
    ],
    requirements: [
      "Currently enrolled in a Bachelor's program",
      "Basic SQL and Excel knowledge",
      "Curiosity about data-driven decision making",
    ],
    skills: ["SQL", "Excel", "Power BI"],
    applyMethod: "one-click",
  },
  {
    id: "job-12",
    title: "Product Designer",
    company: "Studio Aperture",
    companyLogo: "https://logo.clearbit.com/figma.com",
    location: "Bengaluru, Karnataka",
    latitude: 12.9352,
    longitude: 77.6146,
    salaryMin: 900000,
    salaryMax: 1400000,
    salaryPeriod: "year",
    experience: "1-3 years",
    education: "Design degree or equivalent portfolio",
    jobType: "full-time",
    workMode: "hybrid",
    categories: ["design", "full-time", "graduate"],
    postedDate: daysAgo(5),
    deadline: daysFromNow(17),
    description:
      "Own the end-to-end design process for new features on our flagship productivity app.",
    responsibilities: [
      "Lead discovery and design for new features",
      "Run usability tests and iterate on feedback",
      "Partner with PM and engineering on delivery",
    ],
    requirements: [
      "1-3 years of product design experience",
      "Strong portfolio of shipped work",
      "Comfortable presenting design rationale",
    ],
    skills: ["Figma", "User Research", "Prototyping"],
    applyMethod: "external",
    externalApplyUrl: "https://example.com/careers/studio-aperture/product-designer",
  },
  {
    id: "job-13",
    title: "Remote QA Engineer",
    company: "Vertex Cloud Systems",
    companyLogo: "https://logo.clearbit.com/atlassian.com",
    location: "Remote",
    latitude: 17.385,
    longitude: 78.4867,
    salaryMin: 700000,
    salaryMax: 1000000,
    salaryPeriod: "year",
    experience: "1-3 years",
    education: "B.Tech/B.E in Computer Science or equivalent",
    jobType: "full-time",
    workMode: "remote",
    categories: ["it-software", "remote", "full-time"],
    postedDate: daysAgo(4),
    deadline: daysFromNow(19),
    description:
      "Own test automation for our core platform APIs, working fully remote across time zones.",
    responsibilities: [
      "Write and maintain automated test suites",
      "Investigate and triage production bugs",
      "Collaborate with engineers on release readiness",
    ],
    requirements: [
      "1-3 years in QA/test automation",
      "Experience with Cypress, Playwright, or similar",
      "Comfortable working async and remote",
    ],
    skills: ["Cypress", "Playwright", "JavaScript", "CI/CD"],
    applyMethod: "one-click",
  },
  {
    id: "job-14",
    title: "Part-Time Data Entry Operator",
    company: "Civic Records Bureau",
    location: "Secunderabad, Telangana",
    latitude: 17.4399,
    longitude: 78.4983,
    salaryMin: 10000,
    salaryMax: 14000,
    salaryPeriod: "month",
    experience: "fresher",
    education: "Intermediate / Any Bachelor's",
    jobType: "part-time",
    workMode: "on-site",
    categories: ["part-time", "government", "fresher"],
    postedDate: daysAgo(8),
    deadline: daysFromNow(10),
    description:
      "Digitize physical civic records into the government database, 4 hours a day, flexible morning or evening shift.",
    responsibilities: [
      "Enter records accurately into the system",
      "Verify entries against source documents",
      "Report discrepancies to the supervisor",
    ],
    requirements: [
      "Typing speed of at least 30 WPM",
      "Attention to detail",
      "Basic computer literacy",
    ],
    skills: ["Typing", "MS Excel", "Attention to Detail"],
    applyMethod: "external",
    externalApplyUrl: "https://example.gov.in/civic-records/careers",
  },
];

export const sampleProfile: UserProfile = {
  id: "user-1",
  fullName: "Vinayaka Pullayyagari",
  email: "vinayaka@example.com",
  phone: "+91 90000 00000",
  headline: "B.Tech CSE, 2026 | Aspiring Frontend Developer",
  educationLevel: "B.Tech",
  fieldOfStudy: "Computer Science",
  graduationYear: 2026,
  experienceYears: 0,
  skills: ["React", "JavaScript", "HTML", "CSS", "SQL", "Git"],
  preferredCategories: ["internships", "undergraduate", "it-software"],
  preferredWorkModes: ["hybrid", "remote"],
  expectedSalary: 300000,
  resumeFileName: "Vinayaka_Resume.pdf",
  city: "Hyderabad",
  latitude: 17.385,
  longitude: 78.4867,
};

export const sampleApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    appliedDate: daysAgo(1),
    status: "under_review",
    method: "one-click",
  },
  {
    id: "app-2",
    jobId: "job-11",
    appliedDate: daysAgo(3),
    status: "shortlisted",
    method: "one-click",
  },
  {
    id: "app-3",
    jobId: "job-9",
    appliedDate: daysAgo(6),
    status: "applied",
    method: "external",
  },
];

export const categoryLabels: Record<string, string> = {
  internships: "Internships",
  fresher: "Fresher",
  undergraduate: "Undergraduate",
  graduate: "Graduate",
  "part-time": "Part-time",
  "full-time": "Full-time",
  remote: "Remote",
  "it-software": "IT / Software",
  "data-science": "Data Science",
  analytics: "Analytics",
  finance: "Finance",
  marketing: "Marketing",
  design: "Design",
  "customer-support": "Customer Support",
  government: "Government Jobs",
};
